/**
 * Injects story-preview CSS into the editor's document.head so that
 * dialogue previews in the editor reflect the real exported story styles.
 *
 * Single managed style element: #purl-preview-css
 * Content generated by styleCascade.buildAllDialogueCss — same source of
 * truth as story.css produced on export.
 */

import type { Character } from '../types';
import { buildAllDialogueCss } from './styleCascade';

function upsertStyle(id: string, css: string): void {
  let el = document.getElementById(id) as HTMLStyleElement | null;
  if (!el) {
    el = document.createElement('style');
    el.id = id;
    document.head.appendChild(el);
  }
  el.textContent = css;
}

function removeStyle(id: string): void {
  document.getElementById(id)?.remove();
}

export function injectPreviewCSS(characters: Character[]): void {
  const css = buildAllDialogueCss(characters);
  if (css) {
    upsertStyle('purl-preview-css', css);
  } else {
    removeStyle('purl-preview-css');
  }
}

export function removeAllPreviewCSS(): void {
  removeStyle('purl-preview-css');
}
